import type { Author, Narrator, Publisher, Category, MasterBook } from "./types"

export const authors: Author[] = [
  {
    id: "1",
    name: "রবীন্দ্রনাথ ঠাকুর",
    nameEn: "Rabindranath Tagore",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&h=300&fit=crop",
    bio: "বাংলা সাহিত্যের অন্যতম শ্রেষ্ঠ কবি ও সাহিত্যিক। ১৯১৩ সালে সাহিত্যে নোবেল পুরস্কার লাভ করেন।",
    genre: "Poetry & Novels",
    booksCount: 156,
    followers: "2.5M",
    isFeatured: true,
  },
  {
    id: "2",
    name: "শরৎচন্দ্র চট্টোপাধ্যায়",
    nameEn: "Sarat Chandra Chattopadhyay",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop",
    bio: "বাংলা সাহিত্যের অন্যতম জনপ্রিয় ঔপন্যাসিক।",
    genre: "Novels",
    booksCount: 89,
    followers: "1.8M",
    isFeatured: true,
  },
  {
    id: "3",
    name: "সত্যজিৎ রায়",
    nameEn: "Satyajit Ray",
    avatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=300&h=300&fit=crop",
    bio: "বিশ্ববিখ্যাত চলচ্চিত্র নির্মাতা এবং সাহিত্যিক। ফেলুদা ও প্রফেসর শঙ্কু সিরিজের স্রষ্টা।",
    genre: "Mystery & Sci-Fi",
    booksCount: 78,
    followers: "3.2M",
    isFeatured: true,
  },
  {
    id: "4",
    name: "বিভূতিভূষণ বন্দ্যোপাধ্যায়",
    nameEn: "Bibhutibhushan Bandyopadhyay",
    avatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=300&h=300&fit=crop",
    bio: "বাংলা সাহিত্যের অন্যতম শ্রেষ্ঠ কথাসাহিত্যিক। পথের পাঁচালী ও আরণ্যক তাঁর বিখ্যাত রচনা।",
    genre: "Classic Literature",
    booksCount: 42,
    followers: "1.5M",
    isFeatured: true,
  },
  {
    id: "5",
    name: "হুমায়ূন আহমেদ",
    nameEn: "Humayun Ahmed",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&h=300&fit=crop",
    bio: "বাংলাদেশের সবচেয়ে জনপ্রিয় লেখক। হিমু ও মিসির আলি চরিত্রের স্রষ্টা।",
    genre: "Fiction & Drama",
    booksCount: 200,
    followers: "4.5M",
    isFeatured: true,
  },
  {
    id: "6",
    name: "বঙ্কিমচন্দ্র চট্টোপাধ্যায়",
    nameEn: "Bankim Chandra Chattopadhyay",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop",
    bio: "বাংলা উপন্যাসের জনক। বন্দে মাতরম সঙ্গীতের রচয়িতা।",
    genre: "Historical Fiction",
    booksCount: 45,
    followers: "980K",
    isFeatured: false,
  },
  {
    id: "7",
    name: "সুনীল গঙ্গোপাধ্যায়",
    nameEn: "Sunil Gangopadhyay",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&h=300&fit=crop",
    bio: "আধুনিক বাংলা সাহিত্যের অন্যতম প্রধান কবি ও ঔপন্যাসিক।",
    genre: "Modern Poetry",
    booksCount: 120,
    followers: "1.2M",
    isFeatured: false,
  },
  {
    id: "8",
    name: "কাজী নজরুল ইসলাম",
    nameEn: "Kazi Nazrul Islam",
    avatar: "https://images.unsplash.com/photo-1552058544-f2b08422138a?w=300&h=300&fit=crop",
    bio: "বিদ্রোহী কবি। বাংলাদেশের জাতীয় কবি।",
    genre: "Poetry & Songs",
    booksCount: 85,
    followers: "2.8M",
    isFeatured: true,
  },
]

export const narrators: Narrator[] = [
  {
    id: "1",
    name: "সৌমিত্র চট্টোপাধ্যায়",
    nameEn: "Soumitra Chatterjee",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
    bio: "কিংবদন্তি অভিনেতা এবং আবৃত্তিকার।",
    specialty: "Classic Literature",
    audiobooksCount: 45,
    listeners: "125K",
    rating: 4.9,
    isFeatured: true,
  },
  {
    id: "2",
    name: "অপর্ণা সেন",
    nameEn: "Aparna Sen",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop",
    bio: "প্রখ্যাত চলচ্চিত্র পরিচালক ও অভিনেত্রী।",
    specialty: "Drama & Romance",
    audiobooksCount: 38,
    listeners: "98K",
    rating: 4.8,
    isFeatured: true,
  },
  {
    id: "3",
    name: "প্রসেনজিৎ চট্টোপাধ্যায়",
    nameEn: "Prosenjit Chatterjee",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop",
    bio: "বাংলা চলচ্চিত্রের মহানায়ক।",
    specialty: "Thriller & Adventure",
    audiobooksCount: 52,
    listeners: "180K",
    rating: 4.9,
    isFeatured: true,
  },
  {
    id: "4",
    name: "রিতুপর্ণা সেনগুপ্ত",
    nameEn: "Rituparna Sengupta",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop",
    bio: "জনপ্রিয় অভিনেত্রী।",
    specialty: "Poetry & Romance",
    audiobooksCount: 29,
    listeners: "67K",
    rating: 4.7,
    isFeatured: false,
  },
  {
    id: "5",
    name: "বিক্রম ঘোষ",
    nameEn: "Bikram Ghosh",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop",
    bio: "বিখ্যাত তবলাবাদক ও সুরকার।",
    specialty: "Non-Fiction",
    audiobooksCount: 34,
    listeners: "54K",
    rating: 4.6,
    isFeatured: false,
  },
  {
    id: "6",
    name: "স্বস্তিকা মুখোপাধ্যায়",
    nameEn: "Swastika Mukherjee",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop",
    bio: "প্রতিভাবান অভিনেত্রী।",
    specialty: "Children's Stories",
    audiobooksCount: 22,
    listeners: "42K",
    rating: 4.8,
    isFeatured: false,
  },
]

export const publishers: Publisher[] = [
  {
    id: "1",
    name: "আনন্দ পাবলিশার্স",
    nameEn: "Ananda Publishers",
    logo: "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=200&h=200&fit=crop",
    description: "বাংলা সাহিত্যের অন্যতম প্রধান প্রকাশনা সংস্থা।",
    booksCount: 5000,
    isVerified: true,
  },
  {
    id: "2",
    name: "দে'জ পাবলিশিং",
    nameEn: "Dey's Publishing",
    logo: "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=200&h=200&fit=crop",
    description: "বাংলা সাহিত্যের ঐতিহ্যবাহী প্রকাশক।",
    booksCount: 3500,
    isVerified: true,
  },
  {
    id: "3",
    name: "পত্রভারতী",
    nameEn: "Patraborti",
    logo: "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=200&h=200&fit=crop",
    description: "আধুনিক বাংলা সাহিত্যের প্রকাশক।",
    booksCount: 2800,
    isVerified: true,
  },
]

export const categories: Category[] = [
  { id: "1", name: "Classic", nameBn: "ক্লাসিক", icon: "BookOpen", count: "2,500+", color: "from-amber-500/20 to-amber-600/20" },
  { id: "2", name: "Romance", nameBn: "রোমান্স", icon: "Heart", count: "1,800+", color: "from-pink-500/20 to-pink-600/20" },
  { id: "3", name: "Thriller", nameBn: "থ্রিলার", icon: "Sword", count: "1,200+", color: "from-red-500/20 to-red-600/20" },
  { id: "4", name: "Horror", nameBn: "ভৌতিক", icon: "Ghost", count: "650+", color: "from-purple-500/20 to-purple-600/20" },
  { id: "5", name: "Fantasy", nameBn: "ফ্যান্টাসি", icon: "Sparkles", count: "890+", color: "from-blue-500/20 to-blue-600/20" },
  { id: "6", name: "Academic", nameBn: "শিক্ষামূলক", icon: "GraduationCap", count: "1,500+", color: "from-emerald-500/20 to-emerald-600/20" },
  { id: "7", name: "Children", nameBn: "শিশু সাহিত্য", icon: "Baby", count: "980+", color: "from-orange-500/20 to-orange-600/20" },
  { id: "8", name: "History", nameBn: "ইতিহাস", icon: "History", count: "720+", color: "from-stone-500/20 to-stone-600/20" },
  { id: "9", name: "Self-Help", nameBn: "আত্মউন্নয়ন", icon: "Lightbulb", count: "450+", color: "from-yellow-500/20 to-yellow-600/20" },
  { id: "10", name: "Poetry", nameBn: "কবিতা", icon: "Feather", count: "1,100+", color: "from-indigo-500/20 to-indigo-600/20" },
  { id: "11", name: "Music & Arts", nameBn: "সঙ্গীত ও শিল্প", icon: "Music", count: "320+", color: "from-fuchsia-500/20 to-fuchsia-600/20" },
  { id: "12", name: "Travel", nameBn: "ভ্রমণ কাহিনী", icon: "Globe", count: "280+", color: "from-cyan-500/20 to-cyan-600/20" },
]

export const books: MasterBook[] = [
  {
    id: "1",
    title: "পথের পাঁচালী",
    titleEn: "Pather Panchali",
    slug: "pather-panchali",
    author: authors[3],
    publisher: publishers[0],
    category: categories[0],
    cover: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop",
    description: "A masterpiece of Bengali literature.",
    descriptionBn: "বাংলা সাহিত্যের একটি মাস্টারপিস যা গ্রামীণ বাংলায় একটি দরিদ্র ব্রাহ্মণ পরিবারের সংগ্রাম ও স্বপ্নের চিত্র তুলে ধরে।",
    rating: 4.9,
    reviewsCount: 2540,
    totalReads: "125K",
    publishedDate: "1929",
    language: "Bengali",
    tags: ["classic", "family", "rural"],
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    isFree: true,
    formats: {
      ebook: { available: true, price: 0, pages: 324, fileSize: "2.5 MB", previewChapters: 3 },
      audiobook: { available: true, price: 180, duration: "9h 45m", narrator: narrators[0], chapters: 24, quality: "hd" },
      hardcopy: { available: true, price: 350, originalPrice: 450, discount: 22, pages: 324, binding: "paperback", weight: "380g", dimensions: "21 x 14 x 2 cm", inStock: true, stockCount: 156, deliveryDays: 3 },
    },
  },
  {
    id: "2",
    title: "দেবদাস",
    titleEn: "Devdas",
    slug: "devdas",
    author: authors[1],
    publisher: publishers[1],
    category: categories[1],
    cover: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop",
    description: "A tragic love story.",
    descriptionBn: "একটি বিয়োগান্ত প্রেমের গল্প যা দক্ষিণ এশীয় সংস্কৃতিতে অপ্রত্যাশিত প্রেমের প্রতীক হয়ে উঠেছে।",
    rating: 4.8,
    reviewsCount: 1890,
    totalReads: "98K",
    publishedDate: "1917",
    language: "Bengali",
    tags: ["romance", "tragedy", "classic"],
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    isFree: false,
    formats: {
      ebook: { available: true, price: 120, pages: 256, fileSize: "1.8 MB", previewChapters: 2 },
      hardcopy: { available: true, price: 280, originalPrice: 350, discount: 20, pages: 256, binding: "paperback", weight: "320g", dimensions: "20 x 13 x 1.5 cm", inStock: true, stockCount: 89, deliveryDays: 3 },
    },
  },
  {
    id: "3",
    title: "ফেলুদা সমগ্র",
    titleEn: "Feluda Samagra",
    slug: "feluda-samagra",
    author: authors[2],
    publisher: publishers[0],
    category: categories[2],
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop",
    description: "Complete collection of Feluda adventures.",
    descriptionBn: "ফেলুদার সমস্ত অ্যাডভেঞ্চারের সংকলন - সত্যজিৎ রায়ের সৃষ্ট কিংবদন্তি বাংলা গোয়েন্দা।",
    rating: 4.9,
    reviewsCount: 3200,
    totalReads: "210K",
    publishedDate: "1965-1997",
    language: "Bengali",
    tags: ["mystery", "detective", "adventure"],
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    isFree: false,
    formats: {
      ebook: { available: true, price: 250, pages: 892, fileSize: "8.5 MB", previewChapters: 5 },
      audiobook: { available: true, price: 350, duration: "32h 15m", narrator: narrators[2], chapters: 35, quality: "hd" },
      hardcopy: { available: true, price: 550, originalPrice: 700, discount: 21, pages: 892, binding: "hardcover", weight: "1.2kg", dimensions: "24 x 16 x 5 cm", inStock: true, stockCount: 234, deliveryDays: 4 },
    },
  },
  {
    id: "4",
    title: "গীতাঞ্জলি",
    titleEn: "Gitanjali",
    slug: "gitanjali",
    author: authors[0],
    publisher: publishers[0],
    category: categories[9],
    cover: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=400&h=600&fit=crop",
    description: "Nobel Prize-winning collection of spiritual poetry.",
    descriptionBn: "নোবেল পুরস্কারজয়ী আধ্যাত্মিক কবিতা সংকলন যা ঠাকুরকে আন্তর্জাতিক খ্যাতি এনে দিয়েছিল।",
    rating: 5.0,
    reviewsCount: 4500,
    totalReads: "180K",
    publishedDate: "1910",
    language: "Bengali",
    tags: ["poetry", "spiritual", "philosophy"],
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    isFree: true,
    formats: {
      audiobook: { available: true, price: 0, duration: "4h 30m", narrator: narrators[0], chapters: 103, quality: "hd" },
    },
  },
  {
    id: "5",
    title: "হিমু",
    titleEn: "Himu",
    slug: "himu",
    author: authors[4],
    publisher: publishers[2],
    category: categories[0],
    cover: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=400&h=600&fit=crop",
    description: "The adventures of Himu.",
    descriptionBn: "হিমুর অ্যাডভেঞ্চার, একটি রহস্যময় ও দার্শনিক চরিত্র যে ঢাকার রাস্তায় ঘুরে বেড়ায়।",
    rating: 4.9,
    reviewsCount: 5600,
    totalReads: "320K",
    publishedDate: "1993",
    language: "Bengali",
    tags: ["fiction", "philosophy", "modern"],
    isFeatured: true,
    isNew: true,
    isBestseller: true,
    isFree: false,
    formats: {
      ebook: { available: true, price: 200, pages: 412, fileSize: "3.2 MB", previewChapters: 4 },
      audiobook: { available: true, price: 280, duration: "12h 45m", narrator: narrators[2], chapters: 28, quality: "hd" },
      hardcopy: { available: true, price: 420, originalPrice: 500, discount: 16, pages: 412, binding: "paperback", weight: "450g", dimensions: "21 x 14 x 2.5 cm", inStock: true, stockCount: 567, deliveryDays: 3 },
    },
  },
  {
    id: "6",
    title: "চোখের বালি",
    titleEn: "Chokher Bali",
    slug: "chokher-bali",
    author: authors[0],
    publisher: publishers[0],
    category: categories[1],
    cover: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400&h=600&fit=crop",
    description: "A groundbreaking novel exploring complex relationships.",
    descriptionBn: "একটি যুগান্তকারী উপন্যাস যা জটিল সম্পর্ক এবং বাংলা সমাজে নারীদের অবস্থান অন্বেষণ করে।",
    rating: 4.9,
    reviewsCount: 2100,
    totalReads: "145K",
    publishedDate: "1903",
    language: "Bengali",
    tags: ["classic", "women", "society"],
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    isFree: false,
    formats: {
      ebook: { available: true, price: 150, pages: 278, fileSize: "2.1 MB", previewChapters: 3 },
      audiobook: { available: true, price: 180, duration: "8h 45m", narrator: narrators[0], chapters: 22, quality: "hd" },
      hardcopy: { available: true, price: 290, originalPrice: 380, discount: 24, pages: 278, binding: "paperback", weight: "340g", dimensions: "20 x 13 x 1.8 cm", inStock: true, stockCount: 123, deliveryDays: 3 },
    },
  },
  {
    id: "7",
    title: "আরণ্যক",
    titleEn: "Aranyak",
    slug: "aranyak",
    author: authors[3],
    publisher: publishers[1],
    category: categories[0],
    cover: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop",
    description: "A poetic novel about nature.",
    descriptionBn: "বিহারের বনে একজন ম্যানেজারের অভিজ্ঞতা এবং প্রকৃতির সাথে তার সংযোগ নিয়ে একটি কাব্যিক উপন্যাস।",
    rating: 4.8,
    reviewsCount: 1560,
    totalReads: "89K",
    publishedDate: "1939",
    language: "Bengali",
    tags: ["nature", "forest", "classic"],
    isFeatured: true,
    isNew: false,
    isBestseller: false,
    isFree: true,
    formats: {
      ebook: { available: true, price: 0, pages: 298, fileSize: "2.3 MB", previewChapters: 4 },
      audiobook: { available: true, price: 0, duration: "9h 45m", narrator: narrators[2], chapters: 18, quality: "hd" },
    },
  },
  {
    id: "8",
    title: "শ্রীকান্ত",
    titleEn: "Srikanta",
    slug: "srikanta",
    author: authors[1],
    publisher: publishers[0],
    category: categories[0],
    cover: "https://images.unsplash.com/photo-1589998059171-988d887df646?w=400&h=600&fit=crop",
    description: "An autobiographical novel.",
    descriptionBn: "একটি আত্মজীবনীমূলক উপন্যাস যা নায়ক শ্রীকান্তের দুঃসাহসিক অভিযান ও রোমান্টিক কাহিনী অনুসরণ করে।",
    rating: 4.7,
    reviewsCount: 1890,
    totalReads: "76K",
    publishedDate: "1917-1933",
    language: "Bengali",
    tags: ["adventure", "romance", "classic"],
    isFeatured: false,
    isNew: false,
    isBestseller: false,
    isFree: false,
    formats: {
      ebook: { available: true, price: 180, pages: 456, fileSize: "3.8 MB", previewChapters: 3 },
      audiobook: { available: true, price: 250, duration: "12h 20m", narrator: narrators[3], chapters: 32, quality: "hd" },
      hardcopy: { available: true, price: 380, originalPrice: 480, discount: 21, pages: 456, binding: "paperback", weight: "520g", dimensions: "21 x 14 x 3 cm", inStock: true, stockCount: 78, deliveryDays: 4 },
    },
  },
  {
    id: "9",
    title: "অগ্নিবীণা",
    titleEn: "Agni Veena",
    slug: "agni-veena",
    author: authors[7],
    publisher: publishers[0],
    category: categories[9],
    cover: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400&h=600&fit=crop",
    description: "Revolutionary poetry collection.",
    descriptionBn: "বিদ্রোহী কবির বিপ্লবী কবিতা সংকলন যা স্বাধীনতার চেতনা জাগিয়ে তুলেছিল।",
    rating: 4.9,
    reviewsCount: 2340,
    totalReads: "156K",
    publishedDate: "1922",
    language: "Bengali",
    tags: ["poetry", "revolution", "freedom"],
    isFeatured: true,
    isNew: true,
    isBestseller: true,
    isFree: false,
    formats: {
      ebook: { available: true, price: 100, pages: 156, fileSize: "1.2 MB", previewChapters: 5 },
      audiobook: { available: true, price: 150, duration: "3h 30m", narrator: narrators[4], chapters: 22, quality: "hd" },
      hardcopy: { available: true, price: 220, originalPrice: 280, discount: 21, pages: 156, binding: "hardcover", weight: "280g", dimensions: "19 x 12 x 1.5 cm", inStock: true, stockCount: 345, deliveryDays: 3 },
    },
  },
  {
    id: "10",
    title: "মিসির আলি",
    titleEn: "Misir Ali",
    slug: "misir-ali",
    author: authors[4],
    publisher: publishers[2],
    category: categories[3],
    cover: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=400&h=600&fit=crop",
    description: "The complete adventures of Misir Ali.",
    descriptionBn: "মিসির আলির সমস্ত অ্যাডভেঞ্চার, একজন অধ্যাপক যিনি অতিপ্রাকৃত ঘটনা তদন্ত করেন।",
    rating: 4.8,
    reviewsCount: 4200,
    totalReads: "280K",
    publishedDate: "1995",
    language: "Bengali",
    tags: ["paranormal", "mystery", "thriller"],
    isFeatured: true,
    isNew: true,
    isBestseller: true,
    isFree: false,
    formats: {
      ebook: { available: true, price: 220, pages: 520, fileSize: "4.1 MB", previewChapters: 4 },
      audiobook: { available: true, price: 320, duration: "15h 30m", narrator: narrators[2], chapters: 38, quality: "hd" },
      hardcopy: { available: true, price: 480, originalPrice: 600, discount: 20, pages: 520, binding: "paperback", weight: "580g", dimensions: "21 x 14 x 3 cm", inStock: true, stockCount: 432, deliveryDays: 3 },
    },
  },
]

export function getNewReleases() {
  return books.filter(book => book.isNew)
}

export function getFreeBooks() {
  return books.filter(book => book.isFree)
}

export const trendingBooks = books.slice(0, 6).sort((a, b) =>
  parseInt(b.totalReads.replace("K", "000")) - parseInt(a.totalReads.replace("K", "000"))
)

export const popularAudiobooks = books.filter(book => book.formats.audiobook?.available).slice(0, 8)

export const popularHardcopies = books.filter(book => book.formats.hardcopy?.available).slice(0, 8)

export const readingProgress = [
  { id: "1", bookId: "1", format: "ebook" as const, progress: 65, currentPage: 210, lastReadAt: "2 hours ago" },
  { id: "2", bookId: "6", format: "audiobook" as const, progress: 42, currentTime: "3h 20m left", lastReadAt: "Yesterday" },
  { id: "3", bookId: "3", format: "ebook" as const, progress: 88, currentPage: 785, lastReadAt: "Yesterday" },
  { id: "4", bookId: "8", format: "audiobook" as const, progress: 23, currentTime: "8h 45m left", lastReadAt: "3 days ago" },
]
